### ISSUE TITLE
[Issue] Mobs are spawning in the regions where mob-spawning is deny

### ISSUE THREAD

**Issue by bobhenl** [AdvancedPlugins/AdvancedMobs#85]
### Describe the bug

Hello, when you make big region with mob spawning deny, mobs are trying to spawn there & make annoying noice, cause they spawn & are insta killed, but like all the time.

### How to reproduce

Create region, and wait till they start spawning, have sound on.

**Comment by GC-spigot** [comment]
Fixed!

**Comment by JuergenUniVie** [comment]
Unfortunately no, the mobs still get stuck in the region and you have to set mobs-spawning: allow otherwise you just hear the sound the whole time. you can't kill them either...
